In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('creditcard.csv')

In [5]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [9]:
legit = df[df.Class == 0 ]
froud = df[df.Class == 1]

In [10]:
legit.shape

(284315, 31)

In [11]:
froud.shape

(492, 31)

In [12]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [14]:
froud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [15]:
df.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  0.005453   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0      0.002419  0.009637 -0.000987  0.004467  ... -0.000644 -0.001235   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.000024  0.000070  0.000182 -0.000072 -0.000089 -0.000295 -0.000131   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       88.291022  
1      122.211321  

[2 rows x 30 columns]

In [16]:
legit_sample = legit.sample(n=492)

In [18]:
new_df = pd.concat([legit_sample,froud],axis = 0)

In [19]:
new_df.head()

Time        V1        V2        V3        V4        V5        V6  \
265821  162063.0  2.020261  0.081697 -1.612499  0.349503  0.341129 -0.675037   
197576  132080.0  0.039150 -3.275492 -2.222765  2.070414 -0.816851  0.123605   
266891  162526.0 -5.791795  5.395710 -3.467437 -1.173719 -2.017250 -1.771441   
54688    46564.0 -1.465523  1.188959  2.023037  1.179614 -0.860162  0.441162   
184744  126370.0 -0.021049  0.556803 -0.850773  0.279584  0.420755 -0.857052   

              V7        V8        V9  ...       V21       V22       V23  \
265821  0.053702 -0.074659  0.292425  ... -0.306514 -0.835550  0.356906   
197576  1.269461 -0.380284  0.519986  ...  1.014316  0.831903 -0.978656   
266891 -0.816039  2.064712  2.330187  ... -0.032610  1.351808  0.305595   
54688  -0.124622  0.502163  0.643035  ... -0.175731 -0.356957  0.094788   
184744  1.918991 -0.456013 -0.046472  ...  0.104671  0.476137  0.553361   

             V24       V25       V26       V27       V28   Amount  Class  
265821  0.656942 -0.328732  0.144237 -0.069164 -0.039887     0.89      0  
197576  0.698531  0.059518 -0.377288 -0.169551  0.133460  1026.00      0  
266891  0.524953 -0.051426 -0.409566 -0.259513 -1.052003     0.89      0  
54688   0.619242 -0.101304 -0.646653 -0.650084  0.023052    18.50      0  
184744 -0.168491 -1.646619 -1.136080  0.325558  0.292773   159.99      0  

[5 rows x 31 columns]

In [20]:
new_df.shape

(984, 31)

In [21]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [22]:
new_df.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      96445.609756  0.118062  0.022644 -0.051639  0.007255 -0.061630   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0      0.023070 -0.030036 -0.015240 -0.000731  ... -0.005535 -0.055291   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0      0.004433 -0.014467 -0.025385 -0.020475  0.046451 -0.029244 -0.033579   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       85.552846  
1      122.211321  

[2 rows x 30 columns]

In [23]:
x = new_df.drop(columns = 'Class',axis = 1)
x = x.values
y = new_df['Class']

In [24]:
x

array([[ 1.62063000e+05,  2.02026090e+00,  8.16970316e-02, ...,
        -6.91636839e-02, -3.98866213e-02,  8.90000000e-01],
       [ 1.32080000e+05,  3.91504625e-02, -3.27549151e+00, ...,
        -1.69551168e-01,  1.33460404e-01,  1.02600000e+03],
       [ 1.62526000e+05, -5.79179500e+00,  5.39571003e+00, ...,
        -2.59512599e-01, -1.05200261e+00,  8.90000000e-01],
       ...,
       [ 1.69351000e+05, -6.76142671e-01,  1.12636606e+00, ...,
         3.85107449e-01,  1.94361479e-01,  7.78900000e+01],
       [ 1.69966000e+05, -3.11383161e+00,  5.85864172e-01, ...,
         8.84875540e-01, -2.53700319e-01,  2.45000000e+02],
       [ 1.70348000e+05,  1.99197610e+00,  1.58475887e-01, ...,
         2.98758224e-03, -1.53088128e-02,  4.25300000e+01]])

In [25]:
y

265821    0
197576    0
266891    0
54688     0
184744    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 2)

In [27]:
x_train

array([[ 4.09180000e+04, -3.14025954e+00,  3.36734231e+00, ...,
         7.76691266e-01,  3.97557490e-01,  7.60000000e-01],
       [ 1.59287000e+05, -1.23339014e+00, -4.58253843e-01, ...,
         4.74938970e-02, -1.10698782e-01,  2.38000000e+00],
       [ 8.02090000e+04, -4.31525106e+00, -1.03762044e+00, ...,
         7.35318909e-01, -1.32722976e+00,  6.84410000e+02],
       ...,
       [ 4.72000000e+02, -3.04354062e+00, -3.15730712e+00, ...,
        -2.52773123e-01,  3.57642252e-02,  5.29000000e+02],
       [ 1.33230000e+04, -5.45436178e+00,  8.28742056e+00, ...,
         1.57471478e+00,  8.08725205e-01,  1.00000000e+00],
       [ 3.45110000e+04, -3.85506278e-01,  1.11814955e+00, ...,
         2.45037725e-01,  8.93769158e-02,  4.49000000e+00]])

In [29]:
y_train

42007     1
259828    0
133007    0
153156    0
232516    0
         ..
10568     1
27749     1
623       1
9252      1
27343     0
Name: Class, Length: 787, dtype: int64

In [30]:
x_test

array([[ 1.50963000e+05,  2.13045818e+00,  6.82573953e-01, ...,
        -8.29657808e-02, -1.61980778e-02,  7.60000000e-01],
       [ 1.97620000e+04, -1.41791651e+01,  7.42136996e+00, ...,
         2.17190494e+00, -1.39528768e+00,  1.00000000e+00],
       [ 9.39650000e+04, -1.13977267e+01,  7.76395305e+00, ...,
        -1.72206027e+00, -5.74339363e-01,  1.14000000e+01],
       ...,
       [ 2.69310000e+04, -2.25616993e+01,  1.32089043e+01, ...,
         1.50442466e+00,  4.45919826e-01,  9.99900000e+01],
       [ 4.43930000e+04, -4.61746103e+00,  3.66339525e+00, ...,
        -1.83463054e-01, -7.33597032e-02,  1.00000000e+00],
       [ 1.28460000e+05, -2.14457857e+00,  8.95152640e-02, ...,
        -8.80456407e-02, -3.86795590e-01,  3.29000000e+01]])

In [31]:
y_test

241282    0
11343     1
150715    1
104717    0
58761     1
         ..
251881    1
181803    0
15539     1
50211     1
189567    0
Name: Class, Length: 197, dtype: int64

In [32]:
lr = LogisticRegression()

In [33]:
lr.fit(x_train,y_train)

LogisticRegression()

In [34]:
y_pred = lr.predict(x_train)

In [35]:
y_pred

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,

In [37]:
acc = accuracy_score(y_train,y_pred)

In [39]:
print('Accuracy score on Test Data : ', acc)

Accuracy score on Test Data :  0.9479034307496823


In [42]:
#input_data = (172792,-0.533412522,-0.189733337,0.703337367,-0.50627124,-0.012545679,-0.649616686,1.577006254,-0.414650408,0.486179505,-0.915426649,-1.040458335,-0.031513054,-0.188092901,-0.08431647,0.041333455,-0.302620086,-0.660376645,0.167429934,-0.256116871,0.382948105,0.261057331,0.643078438,0.376777014,0.008797379,-0.473648704,-0.818267121,-0.002415309,0.013648914,217)
input_data = (169966,-3.113831607,0.585864172,-5.399730211,1.817092473,-0.840618466,-2.943547791,-2.20800192,1.058732677,-1.63233335,-5.245983838,1.933519537,-5.030464797,-1.127454575,-6.416627976,0.141237234,-2.549498236,-4.614717069,-1.478137941,-0.035480366,0.30627074,0.583275999,-0.269208638,-0.456107773,-0.18365913,-0.328167759,0.60611581,0.88487554,-0.253700319,245)

numpy_array = np.asarray(input_data)

reshaped = numpy_array.reshape(1, -1)

pred = lr.predict(reshaped)
print(pred)
if(pred[0] == 0):
    print("Credit card is Valid.")
else:
    print("Fraudential Credit Card.")

[1]
Fraudential Credit Card.
